### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by johnjohndoe** [cesarferreira/CatKit#2]
Please consider providing a textual **changelog** so it is easier for users to see what changes from version to version.
- [Example changelog of devise](https://github.com/plataformatec/devise/blob/v3.1.1/CHANGELOG.md)
- [Example changelog of cancan](https://github.com/ryanb/cancan/blob/1.6.10/CHANGELOG.rdoc)
- [Example changelog of angular.js](https://github.com/angular/angular.js/blob/v1.1.5/CHANGELOG.md)
- [GitHub offers release notes](https://github.com/jeffkreeftmeijer/fuubar/releases/new)
- [GitHub release notes example of better_errors](https://github.com/charliesome/better_errors/releases)
- [Umweltzone](https://github.com/johnjohndoe/Umweltzone/blob/master/CHANGELOG.md)

**Comment by cesarferreira** [comment]
I'm not planning on changing the API that much, thanks for the tip tho

**Comment by johnjohndoe** [comment]
At least it would be nice to put a **one liner summary** to the [Git tag](https://github.com/cesarferreira/CatKit/releases) whenever you **release a new version**.

**Comment by cesarferreira** [comment]
Sure @johnjohndoe , I didn't wrote a summary because it was before I made it "public" so for the general people the features of 0.3.0 are the baseline of the library, I'll do it from now on, thanks mate

0.3.0 -> https://github.com/cesarferreira/CatKit/releases/tag/0.3.0

**Comment by johnjohndoe** [comment]
:+1:
