### ISSUE TITLE
Could you tell us what is CatKit?

### ISSUE THREAD

**Issue by HanderWei** [cesarferreira/CatKit#3]
@cesarferreira 
Sorry, I could't realize what is CatKit from README.md.
Could you tell us about it and add them to README.md?

**Comment by devrath** [comment]
Yes even i am interested to know .... how can we use this. Is this similar to PICASSO image library ?

**Comment by alorma** [comment]
As far as i know... this library is similar to picasso, but automatic loads cat images

**Comment by GregSaintJean** [comment]
It's a library that loads placeholder images instead of real images. Good for writing code for a  app that doesn't have a content providing backend. For instance, if you were making a messaging app, and you didn't have a cloud backend to store profile pictures, you could use this in it's place.

**Comment by AndroidDeveloperLB** [comment]
I don't understand the sample. It just shows a single image of a cat. Also, when changing orientation, sometimes it doesn't show anything...

**Comment by alorma** [comment]
This lib put images of cats in a ImageViews.

Now, use it in any way you want

**Comment by AndroidDeveloperLB** [comment]
A library, to put cat images on imageViews ?!
I don't get it.

**Comment by alorma** [comment]
Let me tell a history:

Imagine you are making an incredible app, something about people... let's say a contacts app.

So, you need names, mails, phones... and profiles pictures of each contact.

But, your server guy not implemented the photography uploadere neither the whole feature.

But that's a shame! You need to test your layouts! How can i see if images fit's in your ImageViews?

So, you add some fake bitmaps in you res folder... but you need to test to load images from Internet.

Oh oh! What can i do???? Cry? No!

You have CatKit, add this library, and check how images are loaded from internet! You can test image loading, and see adorable kitties in the same time!

Once your server is done, change and move to load real images :)

**Comment by cesarferreira** [comment]
@GregSaintJean and @alorma sumed it up perfectly

@AndroidDeveloperLB read what @GregSaintJean and @alorma said. 

The sample does show something when rotated.. I'm just using the "NO CACHE" option on the sample, obviously it needs to download another image from the web.. because it didn't cache the previous one ;)

**Comment by alorma** [comment]
@cesarferreira you should close the issue :)

**Comment by HanderWei** [comment]
@alorma @cesarferreira  Thanks for your answer!
