### ISSUE TITLE
CatUrl creator

### ISSUE THREAD

**Issue by alorma** [cesarferreira/CatKit#5]
Hi.

If r want to use this lib in anyother downloader like universal, how can i use it?

This lib provides a CatUrl.getCatUrl() method?

**Comment by cesarferreira** [comment]
You can fork it and change from picasso to universal, I just don't see any advantage with universal..

I don't provide any getCatUrl but you can read the code here and create your own -> https://github.com/cesarferreira/CatKit/blob/master/catkit/src/main/java/github/cesarferreira/catkit/CatKit.java

**Comment by alorma** [comment]
Ok i will do a fork.

The think here, is with a generic url generator, i can use any image provider (picasso, aquery, uil), without need to change imports after.

So i can do Picasso.load(Caturl.get())

**Comment by cesarferreira** [comment]
Yeah I see your point, fork it, add a public static method that receives (width, height) and I'll review it ;)
